### ISSUE TITLE
Sorting entries by closest locations SQL error.

### ISSUE THREAD

**Issue by lastgiven** [doublesecretagency/craft-smartmap#48]
Good day, 

I am experiencing an issue with the plugin where it throws an error saying that 
`column "distance" does not exist`

The error page also printed out the SQL that I tried to execute. I went to PostgreSQL to test what the issue could be and the error log showed the following: 

```
ERROR:  column "distance" does not exist
LINE 124:   HAVING "distance" <= 100 
                   ^
SQL state: 42703
Character: 3618
```

I have tried to play around with the SQL but to no avail. 

This is on the latest version of Craft CMS 3. 

Any assistance would be really appreciated.

Below is the TWIG that is used to get the results:

```
{% set target = craft.request.getParam('near') %}				
{% set params = { target: target, range: 100 } %} 
{% set entries = craft.entries.address(params).orderBy('distance').all() %}
<h1>Showing results for "{{ target }}"...</h1>
{% for entry in entries %}
    <h2>{{ entry.title }}</h2>
    <div>
        {{ entry.address.street1 }}<br />
        {{ entry.address.street2 }}<br />
        {{ entry.address.city }},
        {{ entry.address.state }}
        {{ entry.address.zip }}<br />
        <strong>
            {{ entry.address.distance | number_format(1) }}							
            miles away
        </strong>
    </div>
{% else %}
    <h2>No results found</h2>
{% endfor %}
```

![image](https://user-images.githubusercontent.com/24249787/67860679-27b54c00-fb27-11e9-9564-40122526e21c.png)

**Comment by lindseydiloreto** [comment]
Hi there. Which version of Smart Map are you using?

I believe I patched some Postgres issues recently. Just want to make sure you're running the latest & greatest.

**Comment by lastgiven** [comment]
I am running the latest version of smart map.

**Comment by lindseydiloreto** [comment]
Is `address` the exact handle of your address field?

What value are you passing in as the `target`?

**Comment by lastgiven** [comment]
Hi @lindseydiloreto,

Yes the `address` field is the exact field.

I have tried to fill in every single type of target value that you support. 

I have used lng, lat; code, and string. 

What I can try and do today is remove the plugin and install it again.

**Comment by lastgiven** [comment]
I have removed and re-installed the plugin. 

Deleted all my entries and the error still persists, unfortunately. 

Please let me know if you need any additional info from me :)

**Comment by lastgiven** [comment]
Continued playing with the SQL query to see if I can get it to work. 

The issue is with the `HAVING` clause. 

I removed the `HAVING` clause from the query and added a `WHERE` at the end of the SQL query just above the last `ORDER BY` and I got results back. 

I then went into your plugin to check if I can see if I can change anything there to help me just for the time being and was able to get it to work. 

I changed the following function : 
```php
private function _searchCoords(&$query, array $params)
    {
        $filter = $this->_parseFilter($params);
        // Implement haversine formula
        $haversine = $this->_haversine(
            $filter->coords['lat'],
            $filter->coords['lng']
        );
        // Modify subquery
        $query->subQuery
            ->addSelect($haversine.' AS [[distance]]')
            ->andWhere('[[addresses.fieldId]] = :fieldId', [':fieldId' => $filter->fieldId])
            ->having('[[distance]] <= :range', [':range' => $filter->range])
        ;
        // Temporarily store the distance under the field handle
        $query->query->addSelect("[[subquery.distance]] AS [[{$params['fieldHandle']}]]");
    }
```
To this : 
```php
private function _searchCoords(&$query, array $params)
    {
        $filter = $this->_parseFilter($params);
        // Implement haversine formula
        $haversine = $this->_haversine(
            $filter->coords['lat'],
            $filter->coords['lng']
        );
        // Modify subquery
        $query->subQuery
            ->addSelect($haversine.' AS [[distance]]')
            ->andWhere('[[addresses.fieldId]] = :fieldId', [':fieldId' => $filter->fieldId])
        ;
        // Temporarily store the distance under the field handle
        $query->query->addSelect("[[subquery.distance]] AS [[{$params['fieldHandle']}]]");
        $query->query->andWhere('[[distance]] <= :range', [':range' => $filter->range]);
    }
```

Sorry for spamming you so much.

**Comment by lindseydiloreto** [comment]
No problem, I appreciate all of the detail you're providing! 🍺

Did that potential solution work for you? Is it only returning results within the specified range?

This is interesting... I wonder if Postgres handles `HAVING` differently than MySQL.

**Comment by lastgiven** [comment]
Yes, that solution worked perfectly and was able to get it working with Element API as well after that. 

I know that in MySQL that if the `HAVING` clause does not have a `GROUP BY` added that it then acts as a `WHERE` clause but with PostgreSQL it enforces the rule that a `GROUP BY` is required. 

Maybe you can check from the .env file of the project what DB type is used and then add the `HAVING` or `WHERE` at that time without it affecting anything.

**Comment by lindseydiloreto** [comment]
Good to know! I believe Craft itself has some methods that will allow us to easily check the DB type.

I'll spin up a Postgres environment and do some additional testing. Thanks for tracking down the source of the problem!

**Comment by lastgiven** [comment]
Hi @lindseydiloreto 

Sorry for being so quiet. Do you perhaps have any indication on when you would go live with the fix?

**Comment by lastgiven** [comment]
Hi @lindseydiloreto 

I know we have not touched base in a while regarding this issue but is there any new update or not really?

**Comment by ccchapman** [comment]
I am not using Postgres, but receive a similiar error on the latest release (and dev branch.)

```
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'distance' in 'order clause' in /home/vagrant/site/vendor/yiisoft/yii2/db/Command.php:1290
Stack trace:
#0 /home/vagrant/site/vendor/yiisoft/yii2/db/Command.php(1290): PDOStatement->execute()
#1 /home/vagrant/site/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT `element...')
#2 /home/vagrant/site/vendor/yiisoft/yii2/db/Command.php(442): yii\db\Command->queryInternal('fetchAll', 7)
#3 /home/vagrant/site/vendor/yiisoft/yii2/db/Query.php(307): yii\db\Command->queryColumn()
#4 /home/vagrant/site/vendor/craftcms/cms/src/db/Query.php(211): yii\db\Query->column(NULL)
#5 /home/vagrant/site/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1558): craft\db\Query->column(NULL)
#6 /home/vagrant/site/vendor/twig/twig/src/Extension/CoreExtension.php(1495): craft\elements\db\ElementQuery->ids()
#7 /home/vagrant/site/vendor/craftcms/cms/src/helpers/Template.php(105): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\EntryQuery), 'ids', Array, 'method', false, false)
#8 /home/vagrant/site/storage/runtime/compiled_templates/f1/f1c3721ae12baea17d3c70d69b8503df23e5c497e9637847adbc8e3389064fb8.php(137): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\EntryQuery), 'ids', Array, 'method')
#9 /home/vagrant/site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_62ebe8e19a4836cca5507c9faf6aba9f0222027bc5b86d24be1a636d5c3b311a->doDisplay(Array, Array)
#10 /home/vagrant/site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /home/vagrant/site/storage/runtime/compiled_templates/99/99a8c1472c455f2f99a6867c65d669d2e7277917ad9b5e9ff7ca1934636c5300.php(38): Twig\Template->display(Array)
#12 /home/vagrant/site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_77e6f3bc0ed91af6cd130a1fba798390afdc70acf19f1e966ce317737952add6->doDisplay(Array, Array)
#13 /home/vagrant/site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#14 /home/vagrant/site/storage/runtime/compiled_templates/f4/f4cf53cc914839774cc409ab8846659007c5bb04972f6fb7729c56798a4a076a.php(38): Twig\Template->display(Array)
#15 /home/vagrant/site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_a332ba794804d7ad7f0ef714a4a20daddfaa47f3bdbff22a8ed2e6f35fd2c15e->doDisplay(Array, Array)
#16 /home/vagrant/site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#17 /home/vagrant/site/storage/runtime/compiled_templates/b8/b881ec486349f8b24a103486f20b334a90b42be737d6b3ffe882a94e36ee9efe.php(191): Twig\Template->display(Array)
#18 /home/vagrant/site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_f22dd8ced2488b97245b7f00fef4090b6f735e9cef7a9be20466ae8a0d92389e->doDisplay(Array, Array)
#19 /home/vagrant/site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#20 /home/vagrant/site/storage/runtime/compiled_templates/6e/6ebec5f7711c66ca4a152cac937da33055c319d92fdda408462f9e69b5e13663.php(78): Twig\Template->display(Array)
#21 /home/vagrant/site/vendor/twig/twig/src/Template.php(184): __TwigTemplate_43152bbc1af0dbe59e6bb58d03c417b0b3ed262755cedd3dac6df47094eaaf1e->block_main(Array, Array)
#22 /home/vagrant/site/storage/runtime/compiled_templates/8c/8c8264db8770e7d829cd89bf035f51c662a80af7d517c0827f3e9cc063423192.php(165): Twig\Template->displayBlock('main', Array, Array)
#23 /home/vagrant/site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_bf3b8ffbac9ab90a8a90c6170e9f385396691afd204159f8cb9ebff002aae35f->doDisplay(Array, Array)
#24 /home/vagrant/site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#25 /home/vagrant/site/storage/runtime/compiled_templates/6e/6ebec5f7711c66ca4a152cac937da33055c319d92fdda408462f9e69b5e13663.php(49): Twig\Template->display(Array, Array)
#26 /home/vagrant/site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_43152bbc1af0dbe59e6bb58d03c417b0b3ed262755cedd3dac6df47094eaaf1e->doDisplay(Array, Array)
#27 /home/vagrant/site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#28 /home/vagrant/site/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#29 /home/vagrant/site/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#30 /home/vagrant/site/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#31 /home/vagrant/site/vendor/craftcms/cms/src/web/View.php(344): Twig\Environment->render('_entry', Array)
#32 /home/vagrant/site/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('_entry', Array)
#33 /home/vagrant/site/vendor/craftcms/cms/src/web/Controller.php(243): craft\web\View->renderPageTemplate('_entry', Array)
#34 /home/vagrant/site/vendor/craftcms/cms/src/controllers/TemplatesController.php(101): craft\web\Controller->renderTemplate('_entry', Array)
#35 [internal function]: craft\controllers\TemplatesController->actionRender('_entry', Array)
#36 /home/vagrant/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#37 /home/vagrant/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#38 /home/vagrant/site/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('render', Array)
#39 /home/vagrant/site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#40 /home/vagrant/site/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('templates/rende...', Array)
#41 /home/vagrant/site/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#42 /home/vagrant/site/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#43 /home/vagrant/site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#44 /home/vagrant/site/web/index.php(21): yii\base\Application->run()
#45 {main}

Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'distance' in 'order clause'
The SQL being executed was: SELECT `elements`.`id`
FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`, `structureelements`.`structureId`
FROM `craft_elements` `elements`
INNER JOIN `craft_entries` `entries` ON `entries`.`id` = `elements`.`id`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`
INNER JOIN `craft_content` `content` ON (`content`.`elementId` = `elements`.`id`) AND (`content`.`siteId` = `elements_sites`.`siteId`)
LEFT JOIN `craft_smartmap_addresses` `addresses` ON `addresses`.`elementId` = `elements`.`id`
LEFT JOIN `craft_structureelements` `structureelements` ON (`structureelements`.`elementId` = `elements`.`id`) AND (EXISTS (SELECT *
FROM `craft_structures`
WHERE (`id` = `structureelements`.`structureId`) AND (`dateDeleted` IS NULL)))
WHERE (`entries`.`sectionId`='10') AND (`elements_sites`.`siteId`='1') AND (`elements`.`archived`=FALSE) AND (((`elements`.`enabled`=TRUE) AND (`elements_sites`.`enabled`=TRUE)) AND (`entries`.`postDate` <= '2020-01-24 20:37:39') AND ((`entries`.`expiryDate` IS NULL) OR (`entries`.`expiryDate` > '2020-01-24 20:37:39'))) AND (`elements`.`dateDeleted` IS NULL) AND (`elements_sites`.`enabled`=TRUE) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL)
ORDER BY `distance`) `subquery`
INNER JOIN `craft_entries` `entries` ON `entries`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`
INNER JOIN `craft_elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`
INNER JOIN `craft_content` `content` ON `content`.`id` = `subquery`.`contentId`
LEFT JOIN `craft_structureelements` `structureelements` ON (`structureelements`.`elementId` = `subquery`.`elementsId`) AND (`structureelements`.`structureId` = `subquery`.`structureId`)
ORDER BY `distance` in /home/vagrant/site/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /home/vagrant/site/vendor/yiisoft/yii2/db/Command.php(1295): yii\db\Schema->convertException(Object(PDOException), 'SELECT `element...')
#1 /home/vagrant/site/vendor/yiisoft/yii2/db/Command.php(1158): yii\db\Command->internalExecute('SELECT `element...')
#2 /home/vagrant/site/vendor/yiisoft/yii2/db/Command.php(442): yii\db\Command->queryInternal('fetchAll', 7)
#3 /home/vagrant/site/vendor/yiisoft/yii2/db/Query.php(307): yii\db\Command->queryColumn()
#4 /home/vagrant/site/vendor/craftcms/cms/src/db/Query.php(211): yii\db\Query->column(NULL)
#5 /home/vagrant/site/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1558): craft\db\Query->column(NULL)
#6 /home/vagrant/site/vendor/twig/twig/src/Extension/CoreExtension.php(1495): craft\elements\db\ElementQuery->ids()
#7 /home/vagrant/site/vendor/craftcms/cms/src/helpers/Template.php(105): twig_get_attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\EntryQuery), 'ids', Array, 'method', false, false)
#8 /home/vagrant/site/storage/runtime/compiled_templates/f1/f1c3721ae12baea17d3c70d69b8503df23e5c497e9637847adbc8e3389064fb8.php(137): craft\helpers\Template::attribute(Object(craft\web\twig\Environment), Object(Twig\Source), Object(craft\elements\db\EntryQuery), 'ids', Array, 'method')
#9 /home/vagrant/site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_62ebe8e19a4836cca5507c9faf6aba9f0222027bc5b86d24be1a636d5c3b311a->doDisplay(Array, Array)
#10 /home/vagrant/site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#11 /home/vagrant/site/storage/runtime/compiled_templates/99/99a8c1472c455f2f99a6867c65d669d2e7277917ad9b5e9ff7ca1934636c5300.php(38): Twig\Template->display(Array)
#12 /home/vagrant/site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_77e6f3bc0ed91af6cd130a1fba798390afdc70acf19f1e966ce317737952add6->doDisplay(Array, Array)
#13 /home/vagrant/site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#14 /home/vagrant/site/storage/runtime/compiled_templates/f4/f4cf53cc914839774cc409ab8846659007c5bb04972f6fb7729c56798a4a076a.php(38): Twig\Template->display(Array)
#15 /home/vagrant/site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_a332ba794804d7ad7f0ef714a4a20daddfaa47f3bdbff22a8ed2e6f35fd2c15e->doDisplay(Array, Array)
#16 /home/vagrant/site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#17 /home/vagrant/site/storage/runtime/compiled_templates/b8/b881ec486349f8b24a103486f20b334a90b42be737d6b3ffe882a94e36ee9efe.php(191): Twig\Template->display(Array)
#18 /home/vagrant/site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_f22dd8ced2488b97245b7f00fef4090b6f735e9cef7a9be20466ae8a0d92389e->doDisplay(Array, Array)
#19 /home/vagrant/site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#20 /home/vagrant/site/storage/runtime/compiled_templates/6e/6ebec5f7711c66ca4a152cac937da33055c319d92fdda408462f9e69b5e13663.php(78): Twig\Template->display(Array)
#21 /home/vagrant/site/vendor/twig/twig/src/Template.php(184): __TwigTemplate_43152bbc1af0dbe59e6bb58d03c417b0b3ed262755cedd3dac6df47094eaaf1e->block_main(Array, Array)
#22 /home/vagrant/site/storage/runtime/compiled_templates/8c/8c8264db8770e7d829cd89bf035f51c662a80af7d517c0827f3e9cc063423192.php(165): Twig\Template->displayBlock('main', Array, Array)
#23 /home/vagrant/site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_bf3b8ffbac9ab90a8a90c6170e9f385396691afd204159f8cb9ebff002aae35f->doDisplay(Array, Array)
#24 /home/vagrant/site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#25 /home/vagrant/site/storage/runtime/compiled_templates/6e/6ebec5f7711c66ca4a152cac937da33055c319d92fdda408462f9e69b5e13663.php(49): Twig\Template->display(Array, Array)
#26 /home/vagrant/site/vendor/twig/twig/src/Template.php(407): __TwigTemplate_43152bbc1af0dbe59e6bb58d03c417b0b3ed262755cedd3dac6df47094eaaf1e->doDisplay(Array, Array)
#27 /home/vagrant/site/vendor/twig/twig/src/Template.php(380): Twig\Template->displayWithErrorHandling(Array, Array)
#28 /home/vagrant/site/vendor/twig/twig/src/Template.php(392): Twig\Template->display(Array)
#29 /home/vagrant/site/vendor/twig/twig/src/TemplateWrapper.php(45): Twig\Template->render(Array, Array)
#30 /home/vagrant/site/vendor/twig/twig/src/Environment.php(318): Twig\TemplateWrapper->render(Array)
#31 /home/vagrant/site/vendor/craftcms/cms/src/web/View.php(344): Twig\Environment->render('_entry', Array)
#32 /home/vagrant/site/vendor/craftcms/cms/src/web/View.php(393): craft\web\View->renderTemplate('_entry', Array)
#33 /home/vagrant/site/vendor/craftcms/cms/src/web/Controller.php(243): craft\web\View->renderPageTemplate('_entry', Array)
#34 /home/vagrant/site/vendor/craftcms/cms/src/controllers/TemplatesController.php(101): craft\web\Controller->renderTemplate('_entry', Array)
#35 [internal function]: craft\controllers\TemplatesController->actionRender('_entry', Array)
#36 /home/vagrant/site/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#37 /home/vagrant/site/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#38 /home/vagrant/site/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('render', Array)
#39 /home/vagrant/site/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('render', Array)
#40 /home/vagrant/site/vendor/craftcms/cms/src/web/Application.php(299): yii\base\Module->runAction('templates/rende...', Array)
#41 /home/vagrant/site/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('templates/rende...', Array)
#42 /home/vagrant/site/vendor/craftcms/cms/src/web/Application.php(284): yii\web\Application->handleRequest(Object(craft\web\Request))
#43 /home/vagrant/site/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#44 /home/vagrant/site/web/index.php(21): yii\base\Application->run()
#45 {main}
Additional Information:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'distance' in 'order clause'
)
```

**Comment by Timusan** [comment]
Is there any update to this issue? It seems that this plugin is currently broken on PostgreSQL and I have a feeling it might having something to do with this:

https://stackoverflow.com/questions/36105812/unknown-column-in-having-clause

I am getting the error with a fresh install on PostgreSQL and this both with an entry query as with a GraphQL query. I would really like to use this plugin on one of our projects, but this is pretty blocking at the moment.

**Comment by lindseydiloreto** [comment]
@Timusan Very interesting. Did that patch work for you? ^

**Comment by Timusan** [comment]
Well, actually the above fix did 😄 The previous one was untested (did not know Github would be so eager to link in that commit already 😉) and the database checks were incorrect. The above fix combined with the previous commit got it working for me on PostgreSQL (do not have a MySQL server to check at the moment). This is basically a fast implementation of @lastgiven solution above.

Shall I put this total changeset in a PR so other folks can test this on MySQL?

**Comment by lindseydiloreto** [comment]
Ok great, glad to hear it @Timusan!

So now it conducts a proper proximity search (sorted nearest to farthest)? Or did it just suppress any error messages?

Thanks for submitting that fix! Yes please, go ahead and submit it as a PR so other folks can test it as well. 👍

**Comment by lindseydiloreto** [comment]
Perfect, just merged in your fix and pushed everything live! Go ahead and update to the latest (v3.3.5), and let me know if you run into any issues.

Thanks @Timusan, really appreciate your help getting that patched! 🍺
