### ISSUE TITLE
Error during updating using the cli

### ISSUE THREAD

**Issue by E2design** [doublesecretagency/craft-smartmap#60]
Trying to update this server. Server stalls on smartmap error.

```
xxxxxxxx-web-01:~/www/public_html$ ./craft update all
Exception 'Error' with message 'Undefined class constant 'EVENT_REGISTER_EXPORTERS''

in /storage/av06766/www/public_html/vendor/doublesecretagency/craft-smartmap/src/SmartMap.php:98

Stack trace:
#0 /storage/av06766/www/public_html/vendor/yiisoft/yii2/base/BaseObject.php(109): doublesecretagency\smartmap\SmartMap->init()
#1 /storage/av06766/www/public_html/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#2 /storage/av06766/www/public_html/vendor/craftcms/cms/src/base/Plugin.php(130): yii\base\Module->__construct('smart-map', Object(craft\console\Application), Array)
#3 [internal function]: craft\base\Plugin->__construct('smart-map', Object(craft\console\Application), Array)
#4 /storage/av06766/www/public_html/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#5 /storage/av06766/www/public_html/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('doublesecretage...', Array, Array)
#6 /storage/av06766/www/public_html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('doublesecretage...', Array, Array)
#7 /storage/av06766/www/public_html/vendor/craftcms/cms/src/services/Plugins.php(897): yii\BaseYii::createObject(Array, Array)
#8 /storage/av06766/www/public_html/vendor/craftcms/cms/src/services/Plugins.php(230): craft\services\Plugins->createPlugin('smart-map', Array)
#9 /storage/av06766/www/public_html/vendor/craftcms/cms/src/base/ApplicationTrait.php(1375): craft\services\Plugins->loadPlugins()
#10 /storage/av06766/www/public_html/vendor/craftcms/cms/src/console/Application.php(65): craft\console\Application->_postInit()
#11 /storage/av06766/www/public_html/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\console\Application->init()
#12 /storage/av06766/www/public_html/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#13 /storage/av06766/www/public_html/vendor/yiisoft/yii2/console/Application.php(89): yii\base\Application->__construct(Array)
#14 /storage/av06766/www/public_html/vendor/craftcms/cms/src/console/Application.php(54): yii\console\Application->__construct(Array)
#15 [internal function]: craft\console\Application->__construct(Array)
#16 /storage/av06766/www/public_html/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#17 /storage/av06766/www/public_html/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('craft\\console\\A...', Array, Array)
#18 /storage/av06766/www/public_html/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('craft\\console\\A...', Array, Array)
#19 /storage/av06766/www/public_html/vendor/craftcms/cms/bootstrap/bootstrap.php(244): yii\BaseYii::createObject(Array)
#20 /storage/av06766/www/public_html/vendor/craftcms/cms/bootstrap/console.php(33): require('/storage/av0676...')
#21 /storage/av06766/www/public_html/craft(21): require('/storage/av0676...')
#22 {main}
```

**Comment by lindseydiloreto** [comment]
Sorry about that, it's explained relatively well [over here...](https://github.com/doublesecretagency/craft-smartmap/issues/55#issuecomment-624586242)

I'll add some extra info for clarity. 👍
